# Generated by Django 5.0.1 on 2024-02-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Center name")),
                (
                    "address",
                    models.TextField(max_length=500, verbose_name="Center address"),
                ),
            ],
            options={
                "verbose_name": "Center",
                "verbose_name_plural": "Centers",
            },
        ),
    ]
