# Generated by Django 5.0.1 on 2024-02-05 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_alter_campaign_end_date_alter_campaign_start_date"),
        ("center", "0002_storage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="agents",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="center.center"
            ),
        ),
    ]
