# Generated by Django 5.0.1 on 2024-02-05 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0003_alter_campaign_agents_alter_campaign_center"),
        ("center", "0002_storage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="agents",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="center.center",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
