# Generated by Django 5.0.1 on 2024-02-05 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0004_alter_campaign_agents_alter_campaign_center_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "max_capacity",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "reserved",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slot",
                "verbose_name_plural": "Slots",
            },
        ),
    ]
